Repository wormhole-foundation/wormhole-docs, pull requests merged in 2024-12, with the labels that each got.

#161 replace portal bridge for token bridge
  .snippets/code/tutorials/messaging/token-bridge/token-bridge-1.ts
  .snippets/code/tutorials/messaging/token-bridge/token-bridge-2.ts
  tutorials/messaging/.pages
  tutorials/messaging/index.md
  tutorials/messaging/token-bridge.md
Labels: A3 - Quick Fixes

#163 update multigov faq
  build/contract-integrations/multigov/faq.md
Labels: A2 - Maintenance Minor

#159 update ntt faq
  build/contract-integrations/native-token-transfers/faqs.md
Labels: A2 - Maintenance Minor

#164 token bridge faq
  build/contract-integrations/faqs.md
Labels: A2 - Maintenance Minor

#160 Martinh/ntt config update
  build/contract-integrations/native-token-transfers/configuration/access-control.md
  build/contract-integrations/native-token-transfers/configuration/rate-limiting.md
Labels: A2 - Maintenance Minor

#165 ntt troubleshooting
  build/contract-integrations/native-token-transfers/deployment-process/.pages
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
  build/contract-integrations/native-token-transfers/deployment-process/index.md
  build/contract-integrations/native-token-transfers/deployment-process/troubleshooting.md
  variables.yml
Labels: A0 - New Content

#169 updated title to multigov
  tutorials/index.md
Labels: A3 - Quick Fixes

#167 Update start building section and chain configs
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/cctp.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  build/start-building/.pages
  build/start-building/supported-networks.md
  build/start-building/supported-networks/.pages
  build/start-building/supported-networks/algorand.md
  build/start-building/supported-networks/aptos.md
  build/start-building/supported-networks/cosmos.md
  build/start-building/supported-networks/evm.md
  build/start-building/supported-networks/index.md
  build/start-building/supported-networks/near.md
  build/start-building/supported-networks/solana.md
  build/start-building/supported-networks/sui.md
  build/start-building/testnet-faucets.md
Labels: A1 - Maintenance Major

#173 remove misleading comment about ntt program id in ntt solana deployment docs
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A3 - Quick Fixes

#174 bump required solana cli version for ntt
  variables.yml
Labels: A3 - Quick Fixes

#175 chain updates from bumping the sdk to v1.3.0
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  build/applications/wormhole-sdk/wormhole-sdk.md
Labels: A2 - Maintenance Minor

#172 Added hub and spoke description
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A2 - Maintenance Minor

#148 Martinh/xassets
  images/tutorials/by-product/native-token-transfers/multichain-tokens/multichain-token-1.webp
  images/tutorials/by-product/native-token-transfers/multichain-tokens/multichain-token-2.webp
  images/tutorials/by-product/native-token-transfers/multichain-tokens/multichain-token-3.webp
  images/tutorials/by-product/native-token-transfers/multichain-tokens/multichain-token-4.webp
  images/tutorials/by-product/native-token-transfers/multichain-tokens/multichain-token-5.webp
  tutorials/.pages
  tutorials/by-product/.pages
  tutorials/by-product/native-token-transfers/.pages
  tutorials/by-product/native-token-transfers/index.md
  tutorials/by-product/native-token-transfers/multichain-token.md
Labels: A0 - New Content

#171 Martinh/ntt cli commands
  build/contract-integrations/native-token-transfers/.pages
  build/contract-integrations/native-token-transfers/cli-commands.md
Labels: A0 - New Content

#177 add dockerfile & docker-compose.yml for a basic ntt cli setup
  build/contract-integrations/native-token-transfers/deployment-process/troubleshooting.md
Labels: A2 - Maintenance Minor

#178 add link to demo on github for tutorial
  tutorials/by-product/contract-integrations/cross-chain-contracts.md
Labels: A2 - Maintenance Minor

#181 update faqs
  build/contract-integrations/.pages
  build/contract-integrations/faqs.md
  build/contract-integrations/native-token-transfers/faqs.md
Labels: A2 - Maintenance Minor

#180 Ilariae/octicons
  build/applications/index.md
  build/contract-integrations/index.md
  build/start-building/index.md
  build/toolkit/index.md
  learn/fundamentals/index.md
  learn/index.md
Labels: A3 - Quick Fixes
