Repository wormhole-foundation/wormhole-docs, pull requests merged in 2024-09, with the labels that each got.

#37 shortens directory name, updates links and paths
  .snippets/code/build/build-custom-protocol/native-token-transfers/deployment-process/INttToken.sol
  .snippets/code/build/build-custom-protocol/native-token-transfers/deployment-process/initialize.txt
  build/.pages
  build/build-custom-protocol/.pages
  build/build-custom-protocol/gateway.md
  build/build-custom-protocol/get-started/.pages
  build/build-custom-protocol/get-started/choosing-a-relayer/.pages
  build/build-custom-protocol/get-started/choosing-a-relayer/index.md
  build/build-custom-protocol/get-started/choosing-a-relayer/specialized-relayer.md
  build/build-custom-protocol/get-started/choosing-a-relayer/standard-relayer.md
  build/build-custom-protocol/get-started/dev-env.md
  build/build-custom-protocol/get-started/index.md
  build/build-custom-protocol/index.md
  build/build-custom-protocol/native-token-transfers/.pages
  build/build-custom-protocol/native-token-transfers/configuration/.pages
  build/build-custom-protocol/native-token-transfers/configuration/index.md
  build/build-custom-protocol/native-token-transfers/configuration/ntt-access-control.md
  build/build-custom-protocol/native-token-transfers/configuration/ntt-rate-limiting.md
  build/build-custom-protocol/native-token-transfers/deployment-process/.pages
  build/build-custom-protocol/native-token-transfers/deployment-process/index.md
  build/build-custom-protocol/native-token-transfers/deployment-process/ntt-deploy-to-evm.md
  build/build-custom-protocol/native-token-transfers/deployment-process/ntt-deploy-to-solana.md
  build/build-custom-protocol/native-token-transfers/deployment-process/ntt-installation.md
  build/build-custom-protocol/native-token-transfers/deployment-process/ntt-post-deployment.md
  build/build-custom-protocol/native-token-transfers/index.md
  build/build-custom-protocol/onboarding.md
Labels: A3 - Quick Fixes

#33 Ilariae/ftintro
  learn/.pages
  learn/fast-transfers.md
Labels: A0 - New Content

#46 Ilariae/intro update
  .snippets/text/supported-networks.md
  build/start-building/supported-networks/index.md
  learn/fundamentals/architecture.md
  learn/fundamentals/introduction.md
  learn/fundamentals/security.md
  learn/infrastructure/spy.md
  learn/messaging/cctp.md
  learn/messaging/core-contracts.md
  learn/messaging/ntt/ntt-overview.md
Labels: A2 - Maintenance Minor

#52 update the learn section index pages
  .snippets/code/learn/infrastructure/core-contracts/receiving.js
  .snippets/code/learn/infrastructure/core-contracts/sending.js
  build/build-custom-protocol/native-token-transfers/deployment-process/ntt-deploy-to-evm.md
  learn/fundamentals/architecture.md
  learn/fundamentals/index.md
  learn/fundamentals/security.md
  learn/index.md
  learn/infrastructure/.pages
  learn/infrastructure/core-contracts.md
  learn/infrastructure/index.md
  learn/messaging/.pages
  learn/messaging/gateway.md
  learn/messaging/index.md
  learn/messaging/ntt/index.md
  learn/messaging/ntt/ntt-deployment.md
  learn/messaging/ntt/ntt-overview.md
  learn/messaging/ntt/ntt-security.md
  learn/messaging/token-nft-bridge.md
Labels: A0 - New Content

#51 update infrastructure section index pages
  infrastructure/.pages
  infrastructure/index.md
  infrastructure/relayers/.pages
  infrastructure/relayers/index.md
  infrastructure/spy/.pages
  infrastructure/spy/index.md
  infrastructure/spy/run-spy.md
Labels: A0 - New Content

#35 Creates Contribution guide
  .CONTRIBUTING.md
Labels: A0 - New Content

#45 Dawn/build index pages
  build/build-apps/connect/index.md
  build/build-apps/index.md
  build/build-apps/queries/index.md
  build/build-custom-protocol/get-started/choosing-a-relayer/index.md
  build/build-custom-protocol/get-started/index.md
  build/build-custom-protocol/index.md
  build/build-custom-protocol/native-token-transfers/configuration/index.md
  build/build-custom-protocol/native-token-transfers/deployment-process/index.md
  build/build-custom-protocol/native-token-transfers/index.md
  build/index.md
  build/start-building/index.md
  build/toolkit/index.md
  build/toolkit/tilt.md
Labels: A1 - Maintenance Major

#56 fix spacing
  .CONTRIBUTING.md
Labels: A3 - Quick Fixes

#54 Dawn/tutorial index pages
  tutorials/index.md
  tutorials/messaging/index.md
Labels: A2 - Maintenance Minor

#60 Add disclaimer
  README.md
Labels: A3 - Quick Fixes

#57 Eshaben/fix links
  build/applications/queries/use-queries.md
  build/applications/wormhole-sdk.md
  build/chain-integrations/gateway.md
  build/contract-integrations/dev-env.md
  build/contract-integrations/gateway.md
  build/contract-integrations/index.md
  build/reference/consistency-levels.md
  build/start-building/supported-networks/algorand.md
  build/start-building/supported-networks/aptos.md
  build/start-building/supported-networks/cosmwasm.md
  build/start-building/supported-networks/evm.md
  build/start-building/supported-networks/near.md
  build/start-building/supported-networks/solana.md
  build/start-building/supported-networks/sui.md
  build/toolkit/tilt.md
  infrastructure/relayers/index.md
  learn/fundamentals/introduction.md
  learn/infrastructure/core-contracts.md
  learn/infrastructure/index.md
  learn/infrastructure/vaas.md
  tutorials/messaging/cross-chain-contracts.md
Labels: A2 - Maintenance Minor

#59 alphabetize chain names on reference pages
  build/reference/chain-ids.md
  build/reference/consistency-levels.md
  build/reference/contract-addresses.md
Labels: A2 - Maintenance Minor

#61 Add Demo Repos to the Demos Page and the NTT overview page
  build/start-building/demos.md
  learn/messaging/native-token-transfers/overview.md
Labels: A0 - New Content

#66 Minor text edits
  build/start-building/supported-networks/aptos.md
  build/start-building/supported-networks/evm.md
  learn/fundamentals/security.md
Labels: A3 - Quick Fixes

#64 Ilariae/move gateway
  .snippets/code/build/start-building/supported-networks/cosmos/gatewayIBCRelayerConfig.toml
  .snippets/text/build/start-building/supported-networks/cosmos/IBCRelayerAllowlistTemplate.md
  .snippets/text/supported-networks.md
  build/.pages
  build/chain-integrations/.pages
  build/chain-integrations/index.md
  build/start-building/supported-networks/.pages
  build/start-building/supported-networks/cosmos/.pages
  build/start-building/supported-networks/cosmos/cosmos.md
  build/start-building/supported-networks/cosmos/gateway.md
  build/start-building/supported-networks/cosmos/index.md
  build/start-building/supported-networks/index.md
Labels: A2 - Maintenance Minor

#68 update core contracts page
  .snippets/code/build/contract-integrations/core-contracts/receiving.sol
  .snippets/code/build/contract-integrations/core-contracts/sending.sol
  .snippets/code/learn/infrastructure/core-contracts/receiving.js
  .snippets/code/learn/infrastructure/core-contracts/sending.js
  build/contract-integrations/.pages
  build/contract-integrations/core-contracts.md
  build/contract-integrations/index.md
  learn/infrastructure/core-contracts.md
Labels: A1 - Maintenance Major

#55 Ilariae/how to solver
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/auction.js
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/offer-settle.js
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
  build/.pages
  build/contract-integrations/.pages
  build/contract-integrations/fast-transfers/.pages
  build/contract-integrations/fast-transfers/how-to-solver.md
  build/contract-integrations/fast-transfers/index.md
  build/reference/contract-addresses.md
  learn/messaging/index.md
Labels: A0 - New Content

#73 Minor fast transfers updates
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/auction.js
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/offer-settle.js
  build/contract-integrations/.pages
  build/contract-integrations/fast-transfers/.pages
  build/contract-integrations/fast-transfers/how-to-solver.md
  build/contract-integrations/fast-transfers/index.md
  build/contract-integrations/fast-transfers/smart-components.md
  build/contract-integrations/index.md
  learn/messaging/fast-transfers.md
Labels: A2 - Maintenance Minor

#74 Martinh/emitter check token transfer
  .snippets/code/tutorials/messaging/cross-chain-token-transfers/snippet-2.sol
  .snippets/code/tutorials/messaging/cross-chain-token-transfers/snippet-4.ts
  .snippets/code/tutorials/messaging/cross-chain-token-transfers/snippet-7.html
  tutorials/messaging/cross-chain-token-contracts.md
Labels: A2 - Maintenance Minor

#65 Dawn/faucets
  build/start-building/.pages
  build/start-building/index.md
  build/start-building/supported-networks/cosmos/cosmos.md
  build/start-building/supported-networks/evm.md
  build/start-building/testnet-faucets.md
  images/build/start-building/supported-networks/aurora.webp
  images/build/start-building/supported-networks/gnosis.webp
Labels: A0 - New Content

#78 fix the check-mkdocs-build workflow
  .github/workflows/check-mkdocs-build.yml
Labels: A3 - Quick Fixes

#75 Adds intro to Wormhole SDK page
  build/applications/wormhole-sdk.md
Labels: A1 - Maintenance Major

#76 update connect sdk to typescript sdk
  build/start-building/demos.md
  learn/messaging/cctp.md
Labels: A3 - Quick Fixes

#77 Use autogenerated constants
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/cctp.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/nft-bridge.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/supported-networks.md
  build/reference/chain-ids.md
  build/reference/consistency-levels.md
  build/reference/contract-addresses.md
  build/start-building/supported-networks/aptos.md
  build/start-building/supported-networks/cosmos/cosmos.md
  build/start-building/supported-networks/evm.md
  build/start-building/supported-networks/index.md
  build/start-building/supported-networks/near.md
  build/start-building/supported-networks/solana.md
  build/start-building/supported-networks/sui.md
Labels: A1 - Maintenance Major

#79 Quick Start --> better content on Start Building landing page
  build/start-building/index.md
Labels: A1 - Maintenance Major

#62 Add CCTP Page
  .snippets/code/build/contract-integrations/cctp/CCTPReceiver.sol
  .snippets/code/build/contract-integrations/cctp/CCTPSender.sol
  .snippets/code/build/contract-integrations/cctp/CircleIntegration.sol
  .snippets/code/build/contract-integrations/cctp/MessageTransmitter.sol
  .snippets/code/build/contract-integrations/cctp/TokenMessenger.sol
  .snippets/code/build/contract-integrations/cctp/TokenMinter.sol
  .snippets/code/build/contract-integrations/cctp/receivePayloadAndUSDC.sol
  .snippets/code/build/contract-integrations/cctp/sendCrossChainDeposit.sol
  .snippets/code/build/contract-integrations/cctp/sendUSDCWithPayloadToEvm.sol
  .snippets/text/build/contract-integrations/cctp/DepositForBurn-event.md
  .snippets/text/build/contract-integrations/cctp/MessageSent-event.md
  build/contract-integrations/.pages
  build/contract-integrations/cctp.md
  build/contract-integrations/core-contracts.md
  build/contract-integrations/gateway.md
Labels: A0 - New Content

#80 updated supported networks styling
  .snippets/text/supported-networks.md
Labels: A2 - Maintenance Minor

#86 update faucet links
  build/start-building/testnet-faucets.md
Labels: A3 - Quick Fixes

#92 remove content
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/auction.js
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/offer-settle.js
  .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
  .snippets/code/build/contract-integrations/fast-transfers/smart-components/fast-order.sol
  .snippets/code/build/contract-integrations/fast-transfers/smart-components/market-order.sol
  build/contract-integrations/.pages
  build/contract-integrations/fast-transfers/.pages
  build/contract-integrations/fast-transfers/how-to-solver.md
  build/contract-integrations/fast-transfers/index.md
  build/contract-integrations/fast-transfers/smart-components.md
  build/contract-integrations/index.md
  build/reference/contract-addresses.md
  learn/messaging/.pages
  learn/messaging/fast-transfers.md
  learn/messaging/index.md
Labels: A3 - Quick Fixes

#94 updated links from build section
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  build/applications/connect/features.md
  build/applications/connect/overview.md
  build/applications/connect/routes.md
  build/applications/queries/faqs.md
  build/applications/queries/overview.md
  build/applications/queries/use-queries.md
  build/contract-integrations/cctp.md
  build/contract-integrations/core-contracts.md
  build/contract-integrations/dev-env.md
  build/contract-integrations/gateway.md
  build/start-building/supported-networks/algorand.md
  build/start-building/supported-networks/aptos.md
  build/start-building/supported-networks/evm.md
  build/start-building/supported-networks/index.md
  build/start-building/supported-networks/near.md
  build/start-building/supported-networks/solana.md
  build/start-building/supported-networks/sui.md
  build/toolkit/tilt.md
Labels: A1 - Maintenance Major

#90 use more generic class name for chains lists
  .snippets/text/supported-networks.md
  build/start-building/testnet-faucets.md
Labels: A3 - Quick Fixes

#95 add next steps for the NTT docs
  build/contract-integrations/native-token-transfers/deployment-process/post-deployment.md
  learn/messaging/native-token-transfers/index.md
Labels: A2 - Maintenance Minor

#98 contract addresses reference
  tutorials/messaging/cross-chain-contracts.md
Labels: A2 - Maintenance Minor

#100 Updated links pointing at Wormhole's github
  tutorials/messaging/cross-chain-contracts.md
  tutorials/messaging/cross-chain-token-contracts.md
Labels: A3 - Quick Fixes
