Repository wormhole-foundation/wormhole-docs, pull requests merged in 2024-11, with the labels that each got.

#133 removed all cosmos gateway
  .snippets/code/build/applications/wormhole-sdk/cosmos.ts
  build/applications/connect/configuration-v0.md
  build/applications/connect/features.md
  build/applications/connect/routes.md
  build/applications/wormhole-sdk.md
  build/reference/contract-addresses.md
  build/reference/index.md
  build/toolkit/index.md
  learn/fundamentals/glossary.md
  learn/fundamentals/security.md
  learn/messaging/.pages
  learn/messaging/gateway.md
  learn/messaging/index.md
  learn/messaging/native-token-transfers/security.md
Labels: A1 - Maintenance Major

#132 sui tutorial index
  tutorials/messaging/index.md
Labels: A3 - Quick Fixes

#135 add clarifying solana priority fee flag & ntt manager address notes
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A3 - Quick Fixes

#136 added relevant comment related to Solana deployment version
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A2 - Maintenance Minor

#137 connect tutorial adjustement
  tutorials/messaging/sui-connect.md
Labels: A2 - Maintenance Minor

#138 terms standardization
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A2 - Maintenance Minor

#140 Martinh/sepolia chains
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
Labels: A2 - Maintenance Minor

#139 Martinh/portal demo
  .snippets/code/tutorials/messaging/portal-bridge/portal-bridge-1.ts
  .snippets/code/tutorials/messaging/portal-bridge/portal-bridge-2.ts
  tutorials/messaging/.pages
  tutorials/messaging/index.md
  tutorials/messaging/portal-bridge.md
Labels: A0 - New Content

#144 add log size limit flags to spy docs
  infrastructure/spy/run-spy.md
Labels: A3 - Quick Fixes

#145 update ntt links
  build/applications/connect/configuration.md
  build/applications/connect/routes.md
  build/applications/connect/upgrade.md
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
  build/contract-integrations/native-token-transfers/deployment-process/installation.md
  build/contract-integrations/native-token-transfers/faqs.md
Labels: A3 - Quick Fixes

#147 Ilariae/remove nft bridge
  .snippets/text/build/reference/contract-addresses/nft-bridge.md
  build/applications/connect/upgrade.md
  build/contract-integrations/core-contracts.md
  build/contract-integrations/faqs.md
  build/reference/contract-addresses.md
  build/start-building/supported-networks/algorand.md
  build/start-building/supported-networks/aptos.md
  build/start-building/supported-networks/cosmos.md
  build/start-building/supported-networks/evm.md
  build/start-building/supported-networks/near.md
  build/start-building/supported-networks/solana.md
  build/start-building/supported-networks/sui.md
  learn/infrastructure/vaas.md
  learn/messaging/.pages
  learn/messaging/index.md
  learn/messaging/token-bridge.md
  tutorials/messaging/portal-bridge.md
Labels: A1 - Maintenance Major

#125 Martinh/sdk layout
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-0.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-1.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-10.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-11.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-12.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-13.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-14.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-15.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-16.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-17.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-18.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-19.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-2.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-20.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-21.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-22.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-23.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-25.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-26.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-27.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-3.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-4.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-5.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-6.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-7.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-8.ts
  .snippets/code/build/applications/wormhole-sdk/sdk-layout/layout-9.ts
  build/applications/.pages
  build/applications/wormhole-sdk/.pages
  build/applications/wormhole-sdk/index.md
  build/applications/wormhole-sdk/sdk-layout.md
  build/applications/wormhole-sdk/wormhole-sdk.md
  build/toolkit/.pages
  build/toolkit/wormhole-sdk/.pages
  build/toolkit/wormhole-sdk/index.md
Labels: A0 - New Content

#142 Martinh/protocols payloads
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-1.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-2.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-3.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-4.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-5.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-6.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-7.ts
  .snippets/code/build/applications/wormhole-sdk/protocols-payloads/pl-8.ts
  build/applications/wormhole-sdk/.pages
  build/applications/wormhole-sdk/protocols-payloads.md
Labels: A0 - New Content

#156 minor fixes to protocols and payloads page
  build/applications/wormhole-sdk/protocols-payloads.md
Labels: A3 - Quick Fixes

#158 removed old terms from glossary
  learn/fundamentals/glossary.md
Labels: A2 - Maintenance Minor
