Repository wormhole-foundation/wormhole-docs, pull requests merged in 2024-10, with the labels that each got.

#106 added diagrams
  images/learn/infrastructure/vaas/lifetime-vaa-diagram.webp
  images/learn/messaging/gateway/gateway-diagram.webp
  learn/infrastructure/vaas.md
  learn/messaging/gateway.md
Labels: A2 - Maintenance Minor

#109 Martinh/connect v1
  build/applications/connect/.pages
  build/applications/connect/upgrade.md
Labels: A0 - New Content

#112 updated content based on feedback
  build/applications/connect/upgrade.md
Labels: A3 - Quick Fixes

#114 Ilariae/multigov
  build/contract-integrations/.pages
  build/contract-integrations/index.md
  build/contract-integrations/multigov/.pages
  build/contract-integrations/multigov/deployment.md
  build/contract-integrations/multigov/faq.md
  build/contract-integrations/multigov/index.md
  build/contract-integrations/multigov/upgrade.md
  images/learn/governance/multigov-detailed.webp
  images/learn/governance/multigov-high-level.webp
  learn/.pages
  learn/governance/.pages
  learn/governance/architecture.md
  learn/governance/faq.md
  learn/governance/index.md
  learn/governance/overview.md
  learn/index.md
  tutorials/.pages
  tutorials/index.md
  tutorials/multigov/.pages
  tutorials/multigov/index.md
  tutorials/multigov/treasury-proposal.md
Labels: A0 - New Content

#103 Martinh/wallet connect sdk
  .snippets/code/build/applications/wormhole-sdk/ethers.js
  build/applications/connect/configuration.md
  build/applications/wormhole-sdk.md
Labels: A0 - New Content

#101 Martinh/solidity sdk
  .snippets/code/build/toolkit/solidity-sdk/solidity-sdk-1.sol
  .snippets/code/build/toolkit/solidity-sdk/solidity-sdk-2.sol
  .snippets/code/build/toolkit/solidity-sdk/solidity-sdk-3.sol
  .snippets/code/build/toolkit/solidity-sdk/solidity-sdk-4.sol
  .snippets/code/build/toolkit/solidity-sdk/solidity-sdk-5.sol
  build/toolkit/.pages
  build/toolkit/index.md
  build/toolkit/solidity-sdk.md
Labels: A0 - New Content

#119 minor updates
  learn/governance/architecture.md
  learn/governance/overview.md
  tutorials/multigov/index.md
Labels: A3 - Quick Fixes

#117 Martinh/formatted addresses
  .snippets/code/build/reference/formatted-addresses/evm.ts
  .snippets/code/build/reference/formatted-addresses/solana.ts
  build/reference/.pages
  build/reference/index.md
  build/reference/wormhole-formatted-addresses.md
Labels: A0 - New Content

#120 Martinh/connect update 1.0
  .snippets/code/build/applications/connect/configuration/add-token.tsx
  .snippets/code/build/applications/connect/configuration/arbitrary-token.json
  .snippets/code/build/applications/connect/configuration/arbitrary-token.tsx
  .snippets/code/build/applications/connect/configuration/configure-hosted.tsx
  .snippets/code/build/applications/connect/configuration/configure-html.html
  .snippets/code/build/applications/connect/configuration/configure-react-v0.tsx
  .snippets/code/build/applications/connect/configuration/configure-react-v1.tsx
  .snippets/code/build/applications/connect/configuration/custom-coingecko-key.jsx
  .snippets/code/build/applications/connect/configuration/custom-colors-hosted.tsx
  .snippets/code/build/applications/connect/configuration/custom-colors.tsx
  .snippets/code/build/applications/connect/configuration/custom-full.jsx
  .snippets/code/build/applications/connect/configuration/custom-menu.jsx
  .snippets/code/build/applications/connect/configuration/custom-simple-testnet-v0.tsx
  .snippets/code/build/applications/connect/configuration/custom-simple-testnet-v1.jsx
  .snippets/code/build/applications/connect/configuration/custom-simple-v0.jsx
  .snippets/code/build/applications/connect/configuration/custom-simple-v1.jsx
  .snippets/code/build/applications/connect/configuration/custom-tokens-whitelist.jsx
  .snippets/code/build/applications/connect/configuration/index.ts
  .snippets/code/build/applications/connect/configuration/sample-configuration.json
  .snippets/code/build/applications/connect/overview/cdn-with-version.html
  .snippets/code/build/applications/connect/overview/cdn.html
  .snippets/code/build/applications/connect/overview/hosted.js
  .snippets/code/build/applications/connect/overview/import-v0.js
  .snippets/code/build/applications/connect/overview/import-v1.js
  build/applications/connect/configuration-v0.md
  build/applications/connect/configuration.md
  build/applications/connect/overview.md
Labels: A0 - New Content

#122 remove token2022 section from ntt docs
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A3 - Quick Fixes

#121 regenerated tables with unichain info
  .snippets/text/build/reference/contract-addresses/cctp.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/nft-bridge.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  build/applications/queries/use-queries.md
  build/contract-integrations/multigov/faq.md
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
  build/start-building/supported-networks/solana.md
  build/toolkit/cli.md
  build/toolkit/tilt.md
Labels: A0 - New Content

#71 Martinh/cctp tutorial
  .snippets/code/tutorials/messaging/cctp/cctp-sdk-1.ts
  .snippets/code/tutorials/messaging/cctp/cctp-sdk-2.ts
  .snippets/code/tutorials/messaging/cctp/cctp-sdk-3.ts
  .snippets/code/tutorials/messaging/cctp/cctp-sdk-4.ts
  tutorials/messaging/.pages
  tutorials/messaging/cctp.md
  tutorials/messaging/index.md
Labels: A0 - New Content

#93 Martinh/faq
  build/applications/connect/.pages
  build/applications/connect/faqs.md
  build/applications/connect/index.md
  build/applications/queries/faqs.md
  build/contract-integrations/.pages
  build/contract-integrations/faqs.md
  build/contract-integrations/index.md
  build/contract-integrations/native-token-transfers/.pages
  build/contract-integrations/native-token-transfers/faqs.md
  build/contract-integrations/native-token-transfers/index.md
  build/toolkit/.pages
  build/toolkit/faqs.md
  build/toolkit/index.md
Labels: A0 - New Content

#126 update unichain name to remove sepolia on mainnet tables
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
Labels: A3 - Quick Fixes

#127 add setMinter example command to deploy to evm docs
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
Labels: A3 - Quick Fixes

#131 updated code snippets in connect configurations
  build/applications/connect/configuration.md
  build/applications/connect/upgrade.md
Labels: A3 - Quick Fixes

#130 martinh/removed gateway page
  .snippets/code/build/contract-integrations/gateway/GatewayIbcTokenBridgePayload.rs
  .snippets/code/build/contract-integrations/gateway/into-cosmos.ts
  .snippets/code/build/contract-integrations/gateway/out-of-cosmos.ts
  build/contract-integrations/.pages
  build/contract-integrations/gateway.md
  build/contract-integrations/index.md
Labels: A2 - Maintenance Minor
