Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-05, with the labels that each got.

#377 Queries - Get Started page
  .snippets/code/products/queries/get-started/snippet-1.ts
  .snippets/code/products/queries/get-started/snippet-2.html
  products/queries/get-started.md
Labels: A0 - New Content, B0 - Needs Review

#372 Add gitignore step
  llms-full.txt
  tutorials/solidity-sdk/cross-chain-token-contracts.md
  tutorials/typescript-sdk/tokens-via-token-bridge.md
  tutorials/typescript-sdk/usdc-via-cctp.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#386 Update SDK to version 1.17.0
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#375 Connect - Get Started page
  .snippets/code/products/connect/configuration/get-started/App.tsx
  images/products/connect/tutorials/react-dapp/get-started/connect-get-started-01.webp
  products/connect/get-started.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#391 Martinh/settlement grammar fix
  learn/transfers/settlement/architecture.md
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#396 remove Connect from product comparison table
  build/start-building/products.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#381 Messaging - Get Started
  .snippets/code/products/messaging/get-started/terminal-output-01.html
  .snippets/code/products/messaging/get-started/terminal-output-02.html
  .snippets/code/products/messaging/get-started/terminal-output-03.html
  .snippets/code/products/messaging/get-started/terminal-output-04.html
  .snippets/code/products/messaging/get-started/terminal-output-05.html
  images/products/messaging/get-started/messaging-get-started01.webp
  products/messaging/get-started.md
Labels: A0 - New Content, B0 - Needs Review

#402 Staked rpc comment & feature matrix adjustment
  build/transfers/connect/features.md
  build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
  llms-files/llms-connect.txt
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#388 Queries - Overview
  .snippets/text/products/queries/queries-timeline.json
  images/products/queries/overview/overview-1.webp
  products/queries/guides/.pages
  products/queries/guides/submit-response.md
  products/queries/overview.md
Labels: A0 - New Content, B0 - Needs Review

#387 Messaging - Overview
  .DS_Store
  .snippets/text/build/core-messaging/core-messaging-timeline.json
  images/products/messaging/guides/wormhole-relayers/relayer-1.webp
  products/messaging/overview.md
Labels: A0 - New Content, B0 - Needs Review, C2 - High

#397 Multigov - Overview
  .snippets/text/products/multigov/multigov-timeline.json
  products/multigov/concepts/architecture.md
  products/multigov/overview.md
Labels: A0 - New Content, B0 - Needs Review, C2 - High

#379 Multigov - Get Started page
  .snippets/text/products/multigov/deployment-flow-timeline.json
  products/multigov/get-started.md
Labels: A0 - New Content, B0 - Needs Review

#400 Martinh/tutorial supported chains
  llms-full.txt
  tutorials/typescript-sdk/tokens-via-token-bridge.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#399 Update SDK to the latest version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#383 Martinh/update supported networks
  .snippets/text/build/start-building/supported-networks/cctp.md
  .snippets/text/build/start-building/supported-networks/connect.md
  .snippets/text/build/start-building/supported-networks/multigov.md
  .snippets/text/build/start-building/supported-networks/ntt.md
  .snippets/text/build/start-building/supported-networks/settlement.md
  .snippets/text/build/start-building/supported-networks/token-bridge.md
  .snippets/text/supported-networks.md
  build/start-building/supported-networks.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  llms.txt
Labels: A1 - Maintenance Major, B0 - Needs Review

#407 link adjustments
  products/messaging/overview.md
  products/multigov/overview.md
  products/queries/overview.md
Labels: A3 - Quick Fixes, B0 - Needs Review

#380 Typescript SDK - Get Started page
  .snippets/code/tools/typescript-sdk/get-started/snippet-1.ts
  .snippets/code/tools/typescript-sdk/get-started/snippet-2.ts
  .snippets/code/tools/typescript-sdk/get-started/terminal-01.html
  tools/typescript-sdk/get-started.md
Labels: A0 - New Content, B0 - Needs Review

#382 Token Bridge - Get Started page
  .snippets/code/products/token-bridge/get-started/snippet-1.ts
  .snippets/code/products/token-bridge/get-started/snippet-2.ts
  .snippets/code/products/token-bridge/get-started/snippet-3.ts
  .snippets/code/products/token-bridge/get-started/snippet-4.html
  llms-files/llms-multigov.txt
  llms-files/llms-token-bridge.txt
  llms-full.txt
  llms.txt
  products/token-bridge/get-started.md
Labels: A0 - New Content, B0 - Needs Review

#393 Added cctp-bridge overview.md
  .snippets/text/products/reference/cctp/cctp-timeline.json
  products/cctp-bridge/overview.md
Labels: A0 - New Content, B0 - Needs Review

#394 Added connect overview page.
  .snippets/text/products/reference/connect/overview/connect-timeline.json
  products/connect/overview.md
Labels: A0 - New Content, B0 - Needs Review

#395 Added native-token-transfers/overview.md
  .snippets/text/products/reference/ntt/overview/ntt-timeline.json
  products/native-token-transfers/overview.md
Labels: A0 - New Content, B0 - Needs Review

#416 fix spacing
  build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#417 support for seievm mainnet in sdk v1.20.0
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/supported-networks/ntt.md
  .snippets/text/build/start-building/supported-networks/token-bridge.md
  variables.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#415 Message fee
  .snippets/code/build/core-messaging/core-contracts/attestToken.sol
  .snippets/code/build/core-messaging/core-contracts/transferTokens.sol
  .snippets/code/build/core-messaging/core-contracts/transferTokensWithPayload.sol
  .snippets/code/build/transfers/cctp/CircleIntegration.sol
  build/transfers/token-bridge.md
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#418 rollback example changes
  build/transfers/token-bridge.md
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B0 - Needs Review

#414 Update Diagrams
  images/products/multigov/concepts/architecture/architecture-1.webp
  images/products/multigov/concepts/architecture/architecture-2.webp
  images/products/multigov/concepts/architecture/multigov-detailed.webp
  images/products/multigov/concepts/architecture/multigov-high-level.webp
  images/products/native-token-transfers/guides/solana/ntt-solana-guide-1.webp
  images/products/queries/overview/overview-1.webp
  images/products/settlement/concepts/architecture/architecture-2.webp
  products/multigov/concepts/architecture.md
  products/native-token-transfers/guides/deploy-to-solana.md
Labels: A2 - Maintenance Minor, B0 - Needs Review

#422 Token Bridge Payload Structure
  products/token-bridge/concepts/payload-structure.md
Labels: B0 - Needs Review

#410 Overview - Token Bridge
  images/.DS_Store
  images/learn/.DS_Store
  llms-full.txt
  products/token-bridge/overview.md
Labels: A0 - New Content, B0 - Needs Review

#428 Taylor/supported methods
  products/queries/reference/supported-methods.md
Labels: A0 - New Content, B0 - Needs Review

#413 Overview - Native Token Tranfers
  .snippets/text/products/reference/ntt/overview/ntt-timeline.json
  products/native-token-transfers/overview.md
Labels: A0 - New Content, B0 - Needs Review

#420 Overview - Settlement
  products/settlement/guides/.pages
  products/settlement/overview.md
Labels: A0 - New Content, B0 - Needs Review

#436 Pull in latest changes from main to the staging branch
  .snippets/code/build/transfers/cctp/CircleIntegration.sol
  .snippets/code/products/messaging/guides/core-contracts/attestToken.sol
  .snippets/code/products/messaging/guides/core-contracts/transferTokens.sol
  .snippets/code/products/messaging/guides/core-contracts/transferTokensWithPayload.sol
  .snippets/text/build/start-building/supported-networks/cctp.md
  .snippets/text/build/start-building/supported-networks/connect.md
  .snippets/text/build/start-building/supported-networks/multigov.md
  .snippets/text/build/start-building/supported-networks/ntt.md
  .snippets/text/build/start-building/supported-networks/settlement.md
  .snippets/text/build/start-building/supported-networks/token-bridge.md
  .snippets/text/products/reference/chain-ids/chain-ids.md
  .snippets/text/products/reference/consistency-levels/consistency-levels.md
  .snippets/text/products/reference/contract-addresses/core-contracts.md
  .snippets/text/products/reference/contract-addresses/token-bridge.md
  .snippets/text/supported-networks.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  llms.txt
  products/native-token-transfers/guides/deploy-to-solana.md
  products/reference/supported-networks.md
  products/token-bridge/tutorials/transfer-workflow.md
  variables.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#378 Settlement - Get Started page
  .snippets/code/products/settlement/get-started/snippet-1.ts
  .snippets/code/products/settlement/get-started/snippet-2.ts
  .snippets/code/products/settlement/get-started/snippet-3.html
  products/settlement/get-started.md
Labels: A0 - New Content

#432 use queries page
  .snippets/code/products/queries/guides/use-queries/eth-call-initial-request.txt
  .snippets/code/products/queries/guides/use-queries/eth-call-initial-response.txt
  .snippets/code/products/queries/guides/use-queries/query-demo.sol
  .snippets/code/products/queries/guides/use-queries/query-proxy-query-response.jsx
  .snippets/code/products/queries/guides/use-queries/query-request-with-api-key.jsx
  .snippets/code/products/queries/guides/use-queries/test-full.jsx
  .snippets/text/products/queries/queries-timeline.json
  products/queries/guides/.pages
  products/queries/guides/construct-a-query.md
  products/queries/guides/mock-a-query.md
  products/queries/guides/query-request.md
  products/queries/guides/submit-response.md
  products/queries/guides/use-queries.md
  products/queries/guides/verify-response.md
Labels: B0 - Needs Review

#441 Ilariae/todos
  products/cctp-bridge/.pages
  products/cctp-bridge/concepts/.pages
  products/cctp-bridge/concepts/integration.md
  products/cctp-bridge/get-started.md
  products/cctp-bridge/overview.md
  products/connect/get-started.md
  products/connect/overview.md
  products/messaging/get-started.md
  products/messaging/overview.md
  products/multigov/guides/deploy-to-evm.md
  products/native-token-transfers/guides/deploy-to-evm.md
  products/native-token-transfers/guides/deploy-to-solana.md
  products/native-token-transfers/guides/evm-launchpad.md
  products/queries/.pages
  products/queries/concepts/.pages
  products/queries/concepts/rpc-basics.md
  products/token-bridge/get-started.md
Labels: A2 - Maintenance Minor, B0 - Needs Review

#438 clean up ntt
  .snippets/text/products/native-token-transfers/guides/install-ntt-project.md
  products/native-token-transfers/guides/deploy-to-evm.md
  products/native-token-transfers/guides/deploy-to-solana.md
  products/reference/supported-networks.md
Labels: B0 - Needs Review

#442 Ilariae/clean up lists
  products/connect/configuration/data.md
  products/connect/configuration/theme.md
  products/connect/get-started.md
  products/connect/guides/hosted-version.md
  products/connect/guides/upgrade.md
  products/connect/overview.md
  products/messaging/overview.md
  products/multigov/get-started.md
  products/multigov/overview.md
  products/native-token-transfers/get-started.md
  products/native-token-transfers/guides/evm-launchpad.md
  products/native-token-transfers/guides/post-deployment.md
  products/native-token-transfers/overview.md
  products/queries/overview.md
  products/settlement/get-started.md
  products/settlement/overview.md
  products/token-bridge/get-started.md
  products/token-bridge/overview.md
Labels: A2 - Maintenance Minor, B0 - Needs Review

#443 Fix 404s
  .snippets/text/products/connect/overview/connect-timeline.json
  .snippets/text/products/native-token-transfers/overview/ntt-timeline.json
  .snippets/text/products/reference/supported-networks/cctp.md
  .snippets/text/products/reference/supported-networks/connect.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/ntt.md
  .snippets/text/products/reference/supported-networks/settlement.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  README.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  products/cctp-bridge/tutorials/complete-usdc-transfer.md
  products/connect/guides/upgrade.md
  products/messaging/guides/core-contracts.md
  products/messaging/guides/wormhole-relayers.md
  products/messaging/tutorials/cross-chain-contracts.md
  products/multigov/faqs.md
  products/native-token-transfers/faqs.md
  products/native-token-transfers/guides/deploy-to-solana.md
  products/native-token-transfers/guides/post-deployment.md
  products/native-token-transfers/overview.md
  products/products.md
  products/queries/faqs.md
  products/queries/guides/use-queries.md
  products/reference/supported-networks.md
  products/settlement/get-started.md
  products/settlement/guides/liquidity-layer.md
  products/settlement/guides/solver.md
  products/settlement/overview.md
  products/token-bridge/faqs.md
  products/token-bridge/guides/token-bridge-contracts.md
  products/token-bridge/tutorials/transfer-workflow.md
  protocol/architecture.md
  protocol/infrastructure/core-contracts.md
  protocol/infrastructure/guardians.md
  protocol/infrastructure/spy.md
  protocol/introduction.md
  protocol/security.md
  tools/dev-env.md
  tools/solidity-sdk/sdk-reference.md
  tools/typescript-sdk/get-started.md
Labels: A2 - Maintenance Minor

#444 Fix a few more 404s
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/guides/deploy-to-evm.md
  products/queries/get-started.md
Labels: A2 - Maintenance Minor, B0 - Needs Review

#445 update sdk and wh versions
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/start-building/supported-networks/ntt.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  variables.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#440 adjust tokenbridge function & llms generation
  .snippets/code/build/core-messaging/core-contracts/attestToken.sol
  .snippets/code/build/transfers/cctp/CircleIntegration.sol
  build/transfers/token-bridge.md
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#439 adjust solana buffer accounts comment
  build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge
