Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-06, with the labels that each got.

#447 various fixes
  products/connect/configuration/data.md
  products/native-token-transfers/get-started.md
  products/reference/.pages
  products/settlement/.pages
  products/settlement/get-started.md
  products/settlement/guides/.pages
  products/settlement/guides/liquidity-layer.md
  products/settlement/guides/solver.md
  products/settlement/overview.md
  products/settlement/tutorials/.settlement-routes.md
  protocol/infrastructure-guides/run-spy.md
  protocol/introduction.md
  tools/typescript-sdk/guides/vaas-protocols.md
Labels: A3 - Quick Fixes, B0 - Needs Review, C2 - High

#455 Ilariae/update sdk
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/read-only.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/supported-networks/connect.md
  .snippets/text/build/start-building/supported-networks/multigov.md
  .snippets/text/build/start-building/supported-networks/ntt.md
  .snippets/text/build/start-building/supported-networks/token-bridge.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  images/build/.DS_Store
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#452 ecosystem page
  images/protocol/ecosystem/ecosystem-1.webp
  protocol/.pages
  protocol/ecosystem.md
Labels: A0 - New Content, B0 - Needs Review

#454 Martinh/connect tutorial update
  .snippets/code/products/connect/tutorials/react-dapp/snippet-1.js
  .snippets/code/products/connect/tutorials/react-dapp/snippet-2.ts
  products/connect/tutorials/react-dapp.md
Labels: A1 - Maintenance Major, B0 - Needs Review

#458 Update product overview file name
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  llms.txt
  products/.pages
  products/overview.md
  protocol/ecosystem.md
Labels: A3 - Quick Fixes, B0 - Needs Review

#460 Martinh/fix links
  .snippets/text/build/start-building/supported-networks/connect.md
  .snippets/text/build/start-building/supported-networks/multigov.md
  .snippets/text/build/start-building/supported-networks/ntt.md
  .snippets/text/build/start-building/supported-networks/token-bridge.md
  .snippets/text/products/reference/supported-networks/connect.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/ntt.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  products/cctp-bridge/guides/cctp-contracts.md
  products/messaging/guides/wormhole-relayers.md
  tools/solidity-sdk/get-started.md
  tools/solidity-sdk/sdk-reference.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#465 Martinh/add ntt install path step
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/get-started.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#468 Martinh/update sdk v2.1.0
  variables.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#471 Disable solidity sdk docs until v1.0
  ai-resources/ai-resources.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  llms.txt
  products/messaging/get-started.md
  protocol/ecosystem.md
  protocol/introduction.md
  tools/.pages
  tools/.solidity-sdk/.get-started.md
  tools/.solidity-sdk/.pages
  tools/.solidity-sdk/.sdk-reference.md
Labels: A2 - Maintenance Minor, B0 - Needs Review, C2 - High

#478 add the hyperevm warning to all tables
  .snippets/text/build/start-building/supported-networks/multigov.md
  .snippets/text/build/start-building/supported-networks/token-bridge.md
  .snippets/text/products/reference/chain-ids/chain-ids.md
  .snippets/text/products/reference/contract-addresses/core-contracts.md
  .snippets/text/products/reference/contract-addresses/token-bridge.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  .snippets/text/products/reference/testnet-faucets/testnet-faucets.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C2 - High

#477 update links back to github for sdks
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  tools/.solidity-sdk/.get-started.md
  tools/.solidity-sdk/.sdk-reference.md
  tools/typescript-sdk/get-started.md
  tools/typescript-sdk/sdk-reference.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#479 Martinh/aurora contract
  .snippets/text/products/reference/contract-addresses/read-only.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#485 clarify ntt solana hub & spoke chain comment
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/guides/deploy-to-solana.md
Labels: B1 - Ready to Merge
