Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-02, with the labels that each got.

#229 bump sdk version to v1.5.2
  .snippets/text/build/reference/contract-addresses/relayer.md
  variables.yml
Labels: A3 - Quick Fixes, B0 - Needs Review, C2 - High

#223 Replace NTT card with Multichain Assets on the Tutorials by Product index page
  tutorials/by-product/index.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#230 add ntt no wrappers explanation
  learn/messaging/native-token-transfers/overview.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#232 minor connect fix
  build/applications/connect/configuration/configure-data.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#225 Adds LLMS Flow
  .github/workflows/check-llms.yml
  build/applications/connect/configuration-v0.md
  build/applications/connect/configuration-v1.md
  build/contract-integrations/cctp.md
  llms.txt
  scripts/generate_llms.py
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#231 Added vaa clarifications
  learn/infrastructure/vaas.md
  llms.txt
Labels: A3 - Quick Fixes, B0 - Needs Review, C1 - Medium

#233 Ilariae/llms
  llms.txt
  scripts/generate_llms.py
Labels: A2 - Maintenance Minor, B0 - Needs Review

#234 Generalize Script
  llms.txt
  scripts/generate_llms.py
Labels: A3 - Quick Fixes, B0 - Needs Review

#238 Martinh/update sdk v1.7.0
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C2 - High

#240 bump required solana ntt cli version
  build/contract-integrations/native-token-transfers/deployment-process/troubleshooting.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#237 Martinh/wrapped token demo
  .snippets/code/tutorials/by-product/wormhole-sdk/tokens-via-token-bridge/token-bridge-1.ts
  .snippets/code/tutorials/by-product/wormhole-sdk/tokens-via-token-bridge/token-bridge-2.ts
  .snippets/code/tutorials/by-product/wormhole-sdk/tokens-via-token-bridge/token-bridge-3.ts
  llms.txt
  tutorials/by-product/wormhole-sdk/tokens-via-token-bridge.md
Labels: A0 - New Content, B1 - Ready to Merge

#242 Bump SDK version to 1.9.0
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#244 update card arrows
  build/applications/connect/configuration/index.md
  build/applications/connect/index.md
  build/applications/index.md
  build/applications/queries/index.md
  build/applications/wormhole-sdk/index.md
  build/applications/wormhole-sdk/wormhole-sdk.md
  build/contract-integrations/index.md
  build/contract-integrations/multigov/index.md
  build/contract-integrations/native-token-transfers/configuration/index.md
  build/contract-integrations/native-token-transfers/deployment-process/index.md
  build/contract-integrations/native-token-transfers/deployment-process/post-deployment.md
  build/contract-integrations/native-token-transfers/index.md
  build/index.md
  build/reference/index.md
  build/start-building/index.md
  build/toolkit/index.md
  build/toolkit/wormhole-sdk/index.md
  infrastructure/index.md
  infrastructure/relayers/index.md
  infrastructure/spy/index.md
  learn/fundamentals/index.md
  learn/governance/index.md
  learn/index.md
  learn/infrastructure/index.md
  learn/messaging/index.md
  learn/messaging/native-token-transfers/index.md
  llms.txt
  tutorials/by-product/connect/index.md
  tutorials/by-product/contract-integrations/index.md
  tutorials/by-product/index.md
  tutorials/by-product/multichain-assets/index.md
  tutorials/by-product/multigov/index.md
  tutorials/by-product/wormhole-sdk/index.md
  tutorials/index.md
Labels: A3 - Quick Fixes, B0 - Needs Review, C1 - Medium

#245 Semrush Audit February
  build/applications/queries/use-queries.md
  learn/messaging/cctp.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#247 Martinh/read only contracts
  .snippets/text/build/reference/contract-addresses/read-only.md
  build/reference/contract-addresses.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge

#248 Martinh/sdk v1.10.0
  .snippets/text/build/reference/chain-ids/chain-ids.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#249 Fixes LLMS Script
  .github/workflows/check-llms.yml
  llms.txt
  scripts/generate_llms.py
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#252 add sendToEvm comment for consistency level optimizations
  build/contract-integrations/wormhole-relayers.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#246 Ilariae/token bridge build
  build/contract-integrations/.pages
  build/contract-integrations/index.md
  build/contract-integrations/token-bridge.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C1 - Medium

#250 Update index page icons for consistency
  build/reference/index.md
  infrastructure/relayers/index.md
  infrastructure/spy/index.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#254 Ilariae/wormhole settlements
  build/contract-integrations/.pages
  build/contract-integrations/index.md
  build/contract-integrations/settlements/.pages
  build/contract-integrations/settlements/index.md
  build/contract-integrations/settlements/liquidity-layer.md
  build/contract-integrations/settlements/solver.md
  images/learn/messaging/wormhole-settlements/mayan-mctp.webp
  images/learn/messaging/wormhole-settlements/mayan-swift.webp
  images/learn/messaging/wormhole-settlements/settlements-overview.webp
  learn/messaging/.pages
  learn/messaging/index.md
  learn/messaging/wormhole-settlements/.pages
  learn/messaging/wormhole-settlements/architecture.md
  learn/messaging/wormhole-settlements/index.md
  learn/messaging/wormhole-settlements/overview.md
  llms.txt
  tutorials/by-product/.pages
  tutorials/by-product/settlements/.index.md
  tutorials/by-product/settlements/.pages
  tutorials/by-product/settlements/.settlement-routes.md
Labels: A0 - New Content, C2 - High

#255 Ilariae/product table
  build/start-building/.pages
  build/start-building/products.md
  llms.txt
Labels: A0 - New Content, B0 - Needs Review, C2 - High

#258 Update images on the launchpad guide
  build/contract-integrations/native-token-transfers/deployment-process/evm-launchpad.md
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-1.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-10.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-12.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-2.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-3.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-4.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-5.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-6.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-7.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-8.webp
  images/build/contract-integrations/ntt/ntt-launchpad/ntt-launchpad-9.webp
  llms.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review

#259 add link to settlements
  learn/messaging/wormhole-settlements/overview.md
  llms.txt
Labels: A3 - Quick Fixes, B0 - Needs Review, C2 - High
