Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-09, with the labels that each got.

#532 Ilariae/solana shims
  .snippets/code/products/messaging/guides/shims/consume_vaa.rs
  .snippets/code/products/messaging/guides/shims/post_message.rs
  llms-files/llms-basics.txt
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  llms.txt
  products/messaging/.nav.yml
  products/messaging/concepts/.nav.yml
  products/messaging/concepts/solana-shim.md
  products/messaging/guides/.nav.yml
  products/messaging/guides/solana-shims/.nav.yml
  products/messaging/guides/solana-shims/sol-emission.md
  products/messaging/guides/solana-shims/sol-verification.md
  products/messaging/overview.md
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#606 Martinh/update ntt support
  .snippets/text/products/reference/supported-networks/ntt.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High

#608 add question to ntt faq about minting sui tokens after the treasury cap moved to the ntt manager
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/token-transfers/native-token-transfers/faqs.md
Labels: A0 - New Content, B1 - Ready to Merge

#613 Fix 404
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/token-transfers/native-token-transfers/reference/manager/evm.md
Labels: B1 - Ready to Merge, D0 - Broken Links

#623 bump sdk to v3.5.0
  .snippets/text/products/reference/supported-networks/cctp.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/token-transfers/wrapped-token-transfers/guides/attest-tokens.md
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#614 Martinh/update wtt demos
  .snippets/code/products/wrapped-token-transfers/get-started/snippet-2.ts
  .snippets/code/products/wrapped-token-transfers/get-started/snippet-3.ts
  .snippets/code/products/wrapped-token-transfers/tutorials/transfer-workflow/wtt-1.ts
  .snippets/code/products/wrapped-token-transfers/tutorials/transfer-workflow/wtt-3.ts
  llms-files/llms-wtt.txt
  llms-full.txt
  products/token-transfers/wrapped-token-transfers/get-started.md
  products/token-transfers/wrapped-token-transfers/tutorials/transfer-workflow.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#617 Update SDK to the latest version
  .snippets/text/products/reference/supported-networks/cctp.md
  .snippets/text/products/reference/supported-networks/ntt.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/token-transfers/wrapped-token-transfers/guides/attest-tokens.md
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#619 Fix 404
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/token-transfers/native-token-transfers/reference/manager/evm.md
Labels: B1 - Ready to Merge, D0 - Broken Links

#620 Martinh/remove aptos from ntt
  .snippets/text/products/reference/supported-networks/ntt.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High

#626 adjust replay protection comment in the docs
  .snippets/code/products/messaging/guides/wormhole-relayers/receiveWormholeMessages.sol
  llms-files/llms-basics.txt
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/messaging/guides/wormhole-relayers.md
Labels: A2 - Maintenance Minor, B0 - Needs Review, C2 - High

#622 Martinh/tutorial diagrams
  .snippets/code/products/cctp-bridge/tutorials/complete-usdc-transfer/cctp-sdk-1.ts
  .snippets/code/products/cctp-bridge/tutorials/complete-usdc-transfer/cctp-sdk-2.ts
  .snippets/code/products/cctp-bridge/tutorials/complete-usdc-transfer/cctp-sdk-3.ts
  images/products/cctp/tutorials/automatic-cctp-light.webp
  images/products/cctp/tutorials/automatic-cctp.webp
  images/products/wrapped-token-transfers/tutorials/transfer-workflow/manual-wtt-light.webp
  images/products/wrapped-token-transfers/tutorials/transfer-workflow/manual-wtt.webp
  llms-files/llms-cctp.txt
  llms-files/llms-transfer.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/cctp-bridge/tutorials/complete-usdc-transfer.md
  products/token-transfers/wrapped-token-transfers/tutorials/transfer-workflow.md
Labels: A0 - New Content, B1 - Ready to Merge

#629 Martinh/update ntt supported chains
  .snippets/text/products/reference/supported-networks/ntt.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#630 Martinh/add executor contracts
  .snippets/text/products/reference/contract-addresses/executor.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/reference/contract-addresses.md
Labels: A0 - New Content, B0 - Needs Review, C2 - High
