Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-03, with the labels that each got.

#268 Ilariae/settlement ia
  .snippets/code/build/transfers/settlement/placeFastMarketOrder.sol
  .snippets/code/build/transfers/settlement/placeMarketOrder.sol
  .snippets/code/build/transfers/settlement/solver-config.json
  build/transfers/.pages
  build/transfers/settlement/.pages
  build/transfers/settlement/index.md
  build/transfers/settlement/liquidity-layer.md
  build/transfers/settlement/solver.md
  images/learn/transfers/settlement/mayan-mctp.webp
  images/learn/transfers/settlement/mayan-swift.webp
  images/learn/transfers/settlement/settlement-overview.webp
  learn/transfers/.pages
  learn/transfers/settlement/.pages
  learn/transfers/settlement/architecture.md
  learn/transfers/settlement/index.md
  learn/transfers/settlement/overview.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge

#266 Martinh/sdk v1.11.0
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#270 Martinh/light link read only contract
  .snippets/text/build/reference/contract-addresses/read-only.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge

#261 Ilariae/use cases
  build/start-building/.pages
  build/start-building/use-cases.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#264 product page in build section
  build/start-building/products.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#273 sdk update to v.1.11.1
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#267 Martinh/multigov sol architecture
  learn/governance/architecture.md
  learn/governance/index.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#269 Martinh/multigov deployment
  build/contract-integrations/multigov/.pages
  build/contract-integrations/multigov/deploy-to-evm.md
  build/contract-integrations/multigov/deploy-to-solana.md
  build/contract-integrations/multigov/index.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#274 Martinh/multigov upgrade sol
  build/contract-integrations/multigov/.pages
  build/contract-integrations/multigov/index.md
  build/contract-integrations/multigov/upgrade-evm.md
  build/contract-integrations/multigov/upgrade-solana.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#285 Ilariae/consistency
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#286 Multigov repo and change emoji
  build/contract-integrations/multigov/deploy-to-evm.md
  build/start-building/use-cases.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#263 Dawn/connect index makeover
  .snippets/text/build/transfers/connect/connect-timeline.json
  build/transfers/connect/index.md
  build/transfers/connect/overview.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#279 Bring token bridge build into new ia
  build/transfers/.pages
  build/transfers/token-bridge.md
Labels: A2 - Maintenance Minor, B0 - Needs Review

#292 Martinh/update sdk v1.13.2
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/supported-networks.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C2 - High

#278 Ilariae/settlement faq
  build/transfers/settlement/.pages
  build/transfers/settlement/faqs.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C1 - Medium

#281 adds content: build/core messaging/index
  .snippets/text/build/core-messaging/core-messaging-timeline.json
  build/core-messaging/index.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#295 merge the latest from main into new-product-ia
  .github/workflows/check-llms.yml
  .github/workflows/check-mkdocs-build.yml
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/read-only.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  build/core-messaging/wormhole-relayers.md
  build/multigov/.pages
  build/multigov/deploy-to-evm.md
  build/multigov/deploy-to-solana.md
  build/multigov/index.md
  build/multigov/upgrade-evm.md
  build/multigov/upgrade-solana.md
  build/reference/index.md
  build/start-building/.pages
  build/start-building/products.md
  build/start-building/use-cases.md
  build/transfers/native-token-transfers/deployment-process/.pages
  build/transfers/native-token-transfers/deployment-process/evm-launchpad.md
  build/transfers/native-token-transfers/deployment-process/index.md
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-1.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-10.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-11.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-12.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-13.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-14.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-15.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-2.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-3.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-4.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-5.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-6.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-7.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-8.webp
  images/build/transfers/native-token-transfers/deployment-process/evm-launchpad/ntt-launchpad-9.webp
  images/learn/transfers/settlement/architecture/architecture-1.webp
  images/learn/transfers/settlement/architecture/architecture-2.webp
  images/learn/transfers/settlement/architecture/architecture-3.webp
  infrastructure/relayers/index.md
  infrastructure/spy/index.md
  learn/governance/architecture.md
  learn/governance/index.md
  learn/transfers/index.md
  learn/transfers/settlement/.pages
  learn/transfers/settlement/architecture.md
  llms.txt
  scripts/generate_llms.py
  tutorials/by-product/.pages
  tutorials/by-product/settlements/.index.md
  tutorials/by-product/settlements/.pages
  tutorials/by-product/settlements/.settlement-routes.md
  variables.yml
Labels: A1 - Maintenance Major, B0 - Needs Review, C2 - High

#275 Add build/transfers/index page
  .snippets/text/build/transfers/connect/connect-timeline.json
  build/transfers/connect/index.md
  build/transfers/index.md
  llms.txt
Labels: A0 - New Content, B0 - Needs Review

#283 updates learn transfers index
  learn/transfers/index.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#289 new content: build index page
  build/index.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#290 Dawn/learn index
  build/transfers/connect/index.md
  learn/index.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#300 Split contract integration faqs to new pages
  build/contract-integrations/faqs.md
  build/transfers/native-token-transfers/faqs.md
  build/transfers/token-bridge.md
  llms.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review, C2 - High

#299 update consistency level references
  build/core-messaging/core-contracts.md
  build/reference/consistency-levels.md
  build/reference/index.md
  build/toolkit/typescript-sdk/sdk-layout.md
  build/toolkit/typescript-sdk/vaas-protocols.md
  build/toolkit/typescript-sdk/wormhole-sdk.md
  learn/glossary.md
  learn/infrastructure/core-contracts.md
  learn/infrastructure/vaas.md
  learn/transfers/settlement/architecture.md
  llms.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review, C1 - Medium

#303 Martinh/new product ia
  build/contract-integrations/faqs.md
  build/core-messaging/core-contracts.md
  build/reference/consistency-levels.md
  build/reference/index.md
  build/toolkit/typescript-sdk/sdk-layout.md
  build/toolkit/typescript-sdk/vaas-protocols.md
  build/toolkit/typescript-sdk/wormhole-sdk.md
  build/transfers/native-token-transfers/faqs.md
  build/transfers/token-bridge.md
  learn/glossary.md
  learn/infrastructure/core-contracts.md
  learn/infrastructure/vaas.md
  learn/transfers/native-token-transfers/overview.md
  learn/transfers/settlement/architecture.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#309 Martinh/update sdk v1.13.3 new ia
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  llms.txt
Labels: A1 - Maintenance Major, B0 - Needs Review, C2 - High

#311 Resolve merge conflicts for new-product-ia branch
  learn/transfers/settlement/architecture.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#305 Martinh/ntt sol reshape new ia
  build/transfers/native-token-transfers/cli-commands.md
  build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
  build/transfers/native-token-transfers/deployment-process/installation.md
  build/transfers/native-token-transfers/deployment-process/post-deployment.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High

#314 Semrush march fix
  build/transfers/connect/configuration-v0.md
  build/transfers/native-token-transfers/faqs.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#315 update product table to show ntt supports transfers with messages
  build/start-building/products.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#319 Update broken links
  build/core-messaging/wormhole-relayers.md
  build/multigov/deploy-to-evm.md
  build/multigov/upgrade-evm.md
  build/toolkit/typescript-sdk/sdk-layout.md
  build/transfers/native-token-transfers/faqs.md
  learn/glossary.md
  learn/governance/index.md
  learn/infrastructure/relayer.md
  llms.txt
  tutorials/by-product/wormhole-sdk/usdc-via-cctp.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C2 - High

#320 update variables.yml
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#298 Clean up contract controlled transfers
  build/transfers/index.md
  build/transfers/token-bridge.md
  learn/transfers/index.md
  learn/transfers/settlement/architecture.md
  learn/transfers/token-bridge.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C0 - Low

#313 refresh guardians page, update llms
  learn/infrastructure/guardians.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#325 remove ntt devnet initialization, as for Solana devnet also the ntt testnet config is working
  build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
  llms.txt
  scripts/generate_llms.py
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#321 Refresh build ntt index page
  .snippets/text/build/transfers/ntt/ntt-deployment-process-timeline.json
  build/transfers/native-token-transfers/index.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#293 Refine VAA page
  learn/infrastructure/vaas.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#324 refresh infra architecture, updates llms
  learn/infrastructure/architecture.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#328 downgrade wh version
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#327 Martinh/update sdk v1.14.0
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/build/start-building/testnet-faucets/testnet-faucets.md
  .snippets/text/supported-networks.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#329 rename llms to llms-full
  .github/workflows/check-llms.yml
  llms-full.txt
  scripts/generate_llms.py
Labels: A2 - Maintenance Minor, B0 - Needs Review
