Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-04, with the labels that each got.

#337 Martinh/tilt fix
  build/queries/use-queries.md
  build/toolkit/dev-env.md
  build/toolkit/index.md
  llms-full.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review

#333 add generic headers
  llms-full.txt
  tutorials/by-product/index.md
  tutorials/index.md
Labels: A3 - Quick Fixes, B0 - Needs Review

#322 refreshes spy page, updates llms
  learn/infrastructure/spy.md
  llms-full.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#331 updates ntt index & install with token creation info
  build/transfers/native-token-transfers/deployment-process/installation.md
  build/transfers/native-token-transfers/index.md
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#341 update sdk to latest version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#347 bump cli version again
  variables.yml
Labels: B1 - Ready to Merge, C2 - High

#349 update sdk version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#338 Martinh/llm resources page
  learn/.pages
  learn/ai-resources.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#340 add settlement to product table
  build/start-building/products.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C2 - High

#354 fix start building page
  build/start-building/index.md
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#353 revert start building index page
  build/start-building/index.md
  llms-full.txt
Labels: A3 - Quick Fixes, B0 - Needs Review, C2 - High

#357 update wormhole version to 2.33.0
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#358 Martinh/relayer sdk note
  build/infrastructure/relayers/run-relayer.md
  llms-files/llms-relayers.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#362 update sdk to latest version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#363 Martinh/llm removal learn
  learn/.pages
  learn/ai-resources.md
  llms-full.txt
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#366 Martinh/token router contracts
  build/reference/contract-addresses.md
  build/transfers/settlement/liquidity-layer.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A0 - New Content, B1 - Ready to Merge

#370 Update sdk to latest version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#371 Martinh/guardians spelling fix
  learn/infrastructure/guardians.md
  llms-files/llms-basics.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#374 Update SDK to the latest version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge
