Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-07, with the labels that each got.

#489 Martinh/fix 404s
  .snippets/text/products/reference/consistency-levels/consistency-levels.md
  .snippets/text/products/reference/supported-networks/cctp.md
  .snippets/text/products/reference/supported-networks/connect.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/ntt.md
  .snippets/text/products/reference/supported-networks/settlement.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  llms-full.txt
  products/connect/configuration/configuration-v0.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#494 Martinh/read only
  .snippets/text/products/reference/contract-addresses/read-only.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  variables.yml
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#493 Martinh/cctp supported networks
  .snippets/text/products/reference/supported-networks/cctp.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#500 adds llms-transfer to page, updates llms
  ai-resources/ai-resources.md
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#506 Martinh/update sdk v2.4.0
  .snippets/text/products/reference/chain-ids/chain-ids.md
  .snippets/text/products/reference/consistency-levels/consistency-levels.md
  .snippets/text/products/reference/contract-addresses/core-contracts.md
  .snippets/text/products/reference/contract-addresses/token-bridge.md
  .snippets/text/products/reference/supported-networks/cctp.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  .snippets/text/products/reference/testnet-faucets/testnet-faucets.md
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#510 adjust the solana ntt deployment docs to the new cli commands for setting the mint authority + demo-ntt-connect comment from vite to nextjs
  llms-files/llms-cctp.txt
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/guides/deploy-to-solana.md
  products/native-token-transfers/guides/post-deployment.md
Labels: B1 - Ready to Merge

#486 Martinh/cctp automatic get started
  .snippets/code/products/cctp-bridge/get-started/snippet-2.ts
  .snippets/code/products/cctp-bridge/get-started/snippet-3.html
  llms-files/llms-transfer.txt
  llms-full.txt
  products/cctp-bridge/get-started.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#507 Martinh/update wallet connect
  .snippets/code/products/connect/configuration/data/wallet-connect.tsx
  llms-files/llms-connect.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/connect/configuration/data.md
  products/connect/tutorials/react-dapp.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#359 Ilariae/update llms
  llms-files/llms-basics.txt
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-solidity-sdk.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  llms.txt
  products/messaging/get-started.md
  products/messaging/tutorials/cross-chain-contracts.md
  products/messaging/tutorials/cross-chain-token-contracts.md
  products/messaging/tutorials/replace-signatures.md
  products/token-bridge/concepts/payload-structure.md
  products/token-bridge/concepts/transfer-flow.md
  products/token-bridge/faqs.md
  products/token-bridge/get-started.md
  products/token-bridge/guides/token-bridge-contracts.md
  products/token-bridge/overview.md
  products/token-bridge/portal/faqs.md
  products/token-bridge/reference/supported-networks.md
  products/token-bridge/tutorials/multichain-token.md
  products/token-bridge/tutorials/transfer-workflow.md
  scripts/generate_llms_by_category.py
  scripts/generate_llms_standard.py
  scripts/llms_config.json
  tools/.solidity-sdk/.get-started.md
  tools/.solidity-sdk/.sdk-reference.md
  tools/typescript-sdk/get-started.md
  tools/typescript-sdk/guides/protocols-payloads.md
  tools/typescript-sdk/guides/sdk-layout.md
  tools/typescript-sdk/guides/vaas-protocols.md
  tools/typescript-sdk/sdk-reference.md
Labels: A2 - Maintenance Minor, B0 - Needs Review, C2 - High

#511 SEO July
  .snippets/text/products/reference/supported-networks/connect.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/ntt.md
  .snippets/text/products/reference/supported-networks/settlement.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  llms-files/llms-cctp.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  products/cctp-bridge/get-started.md
  products/cctp-bridge/guides/cctp-contracts.md
  products/cctp-bridge/overview.md
  products/native-token-transfers/get-started.md
  products/native-token-transfers/guides/deploy-to-solana.md
  products/queries/reference/supported-methods.md
  tools/typescript-sdk/sdk-reference.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#521 update sdk to the latest version
  .snippets/text/products/reference/chain-ids/chain-ids.md
  .snippets/text/products/reference/contract-addresses/core-contracts.md
  .snippets/text/products/reference/testnet-faucets/testnet-faucets.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  variables.yml
Labels: A1 - Maintenance Major, B0 - Needs Review

#481 Creates "Fetch a Signed VAA" guide under Token Bridge section
  .snippets/code/products/token-bridge/guides/fetch-signed-vaa/fetch-vaa.ts
  .snippets/code/products/token-bridge/guides/fetch-signed-vaa/terminal-1.html
  images/products/token-bridge/guides/fetch-vaa/fetch-vaa-1.webp
  images/products/token-bridge/guides/fetch-vaa/fetch-vaa-2.webp
  llms-files/llms-transfer.txt
  llms-full.txt
  llms.txt
  products/token-bridge/guides/.pages
  products/token-bridge/guides/fetch-signed-vaa.md
Labels: A0 - New Content, B1 - Ready to Merge

#524 Dependency upgrade
  .CONTRIBUTING.md
  .nav.yml
  ai-resources/.nav.yml
  products/.nav.yml
  products/cctp-bridge/.nav.yml
  products/cctp-bridge/guides/.nav.yml
  products/cctp-bridge/reference/.nav.yml
  products/cctp-bridge/tutorials/.nav.yml
  products/connect/.nav.yml
  products/connect/concepts/.nav.yml
  products/connect/configuration/.nav.yml
  products/connect/guides/.nav.yml
  products/connect/reference/.nav.yml
  products/connect/tutorials/.nav.yml
  products/messaging/.nav.yml
  products/messaging/guides/.nav.yml
  products/messaging/tutorials/.nav.yml
  products/multigov/.nav.yml
  products/multigov/concepts/.nav.yml
  products/multigov/guides/.nav.yml
  products/multigov/reference/.nav.yml
  products/multigov/tutorials/.nav.yml
  products/native-token-transfers/.nav.yml
  products/native-token-transfers/concepts/.nav.yml
  products/native-token-transfers/configuration/.nav.yml
  products/native-token-transfers/guides/.nav.yml
  products/native-token-transfers/reference/.nav.yml
  products/queries/.nav.yml
  products/queries/guides/.nav.yml
  products/queries/reference/.nav.yml
  products/reference/.nav.yml
  products/settlement/.nav.yml
  products/settlement/concepts/.nav.yml
  products/settlement/reference/.nav.yml
  products/token-bridge/.nav.yml
  products/token-bridge/concepts/.nav.yml
  products/token-bridge/guides/.nav.yml
  products/token-bridge/reference/.nav.yml
  products/token-bridge/tutorials/.nav.yml
  protocol/.nav.yml
  protocol/infrastructure-guides/.nav.yml
  protocol/infrastructure/.nav.yml
  tools/.nav.yml
  tools/.solidity-sdk/.nav.yml
  tools/cli/.nav.yml
  tools/typescript-sdk/.nav.yml
  tools/typescript-sdk/guides/.nav.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#534 ntt: adjust solana cli set-mint-authority command to comply with rece…
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/guides/deploy-to-solana.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High
