Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-01, with the labels that each got.

#183 Create CODEOWNERS
  .github/CODEOWNERS
Labels: A2 - Maintenance Minor

#184 Martinh/solscan faq
  build/contract-integrations/faqs.md
Labels: A0 - New Content

#182 Martinh/internal contributors
  build/toolkit/.pages
Labels: A2 - Maintenance Minor

#187 remove question from faq
  build/contract-integrations/native-token-transfers/faqs.md
Labels: A3 - Quick Fixes

#185 add check repositories action
  .github/scripts/check_repositories.py
  .github/scripts/create_issues.py
  .github/workflows/check-repositories.yaml
  variables.yml
Labels: A0 - New Content

#191 fix link
  build/start-building/index.md
Labels: A3 - Quick Fixes, B0 - Needs Review

#189 Martinh/ntt learn to build
  learn/messaging/native-token-transfers/overview.md
Labels: A0 - New Content, B1 - Ready to Merge

#192 added links to ntt post deployment
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#195 Update sdk version in the variables.yml
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#196 add cctp index card
  build/contract-integrations/index.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#197 Martinh/bump sdk version
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#200 Update version variable
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#204 Martinh/update sdk version
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#201 Update links
  build/applications/queries/faqs.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#203 add diagram explanation
  learn/fundamentals/architecture.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#209 Martinh/vaas protocols
  .snippets/code/build/applications/wormhole-sdk/vaas-protocols/solidity-sdk.sol
  .snippets/code/build/applications/wormhole-sdk/vaas-protocols/ts-sdk.ts
  build/applications/wormhole-sdk/.pages
  build/applications/wormhole-sdk/vaas-protocols.md
Labels: A0 - New Content, B1 - Ready to Merge

#210 Martinh/new chain
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/relayer.md
  .snippets/text/supported-networks.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#211 martinh/update graphic
  images/learn/fundamentals/introduction/introduction-1.webp
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#205 create a warning to create token metadata before delegating mint authority to solana ntt docs
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#216 add solana buffer account docs reference to sol ntt deployment
  build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#199 Site health improvements - january report
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/supported-networks.md
  build/applications/connect/overview.md
  build/toolkit/index.md
  build/toolkit/tilt.md
  tutorials/by-product/connect/react-dapp.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#213 ntt fix
  learn/messaging/native-token-transfers/deployment.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C0 - Low

#217 Ilariae/video
  build/contract-integrations/native-token-transfers/deployment-process/installation.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C1 - Medium

#219 Martinh/js tutorial to ts
  .snippets/code/tutorials/by-product/contract-integrations/cross-chain-contracts/snippet-3.ts
  .snippets/code/tutorials/by-product/contract-integrations/cross-chain-contracts/snippet-4.html
  .snippets/code/tutorials/by-product/contract-integrations/cross-chain-contracts/snippet-5.ts
  .snippets/code/tutorials/by-product/contract-integrations/cross-chain-contracts/snippet-6.ts
  .snippets/code/tutorials/by-product/contract-integrations/cross-chain-contracts/snippet-8.html
  tutorials/by-product/contract-integrations/cross-chain-contracts.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#220 Martinh/reorg create tokens guide
  tutorials/by-product/.pages
  tutorials/by-product/multichain-assets/.pages
  tutorials/by-product/multichain-assets/index.md
  tutorials/by-product/multichain-assets/multichain-token.md
  tutorials/by-product/native-token-transfers/.pages
  tutorials/by-product/native-token-transfers/index.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#222 update scripts and sdk version
  .snippets/text/build/reference/chain-ids/chain-ids.md
  .snippets/text/build/reference/consistency-levels/consistency-levels.md
  .snippets/text/build/reference/contract-addresses/core-contracts.md
  .snippets/text/build/reference/contract-addresses/token-bridge.md
  .snippets/text/supported-networks.md
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge
