Repository wormhole-foundation/wormhole-docs, pull requests merged in 2025-08, with the labels that each got.

#546 Martinh/demo sdk version
  llms-files/llms-token-bridge.txt
  llms-full.txt
  products/token-bridge/get-started.md
  products/token-bridge/tutorials/transfer-workflow.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High

#547 Update section name to "Deploy to SVM Chains"
  .snippets/text/products/native-token-transfers/overview/ntt-timeline.json
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  llms.txt
  products/native-token-transfers/concepts/architecture.md
  products/native-token-transfers/faqs.md
  products/native-token-transfers/get-started.md
  products/native-token-transfers/guides/.nav.yml
  products/native-token-transfers/guides/deploy-to-solana.md
  products/native-token-transfers/guides/post-deployment.md
  products/native-token-transfers/guides/troubleshoot.md
  products/native-token-transfers/overview.md
  products/native-token-transfers/reference/managers-transceivers.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#549 remove mention of nft
  .snippets/code/tools/cli/get-started/near.txt
  llms-files/llms-basics.txt
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  protocol/introduction.md
  tools/cli/get-started.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#559 Martinh/update sdk v3.2.0
  .snippets/text/products/reference/chain-ids/chain-ids.md
  .snippets/text/products/reference/consistency-levels/consistency-levels.md
  .snippets/text/products/reference/contract-addresses/core-contracts.md
  .snippets/text/products/reference/contract-addresses/token-bridge.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/ntt.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  .snippets/text/products/reference/testnet-faucets/testnet-faucets.md
  variables.yml
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High

#545 Create PR Link Check
  .github/scripts/pr-link-checker.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#569 Add `dev` to workflows
  .github/workflows/check-llms.yml
  .github/workflows/check-mkdocs-build.yml
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#579 chain id link fix
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
  products/reference/chain-ids.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#576 update sdk to the latest version
  variables.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#466 Ilariae/clean ntt
  .snippets/code/products/native-token-transfers/guides/deploy-to-evm/terminal01.html
  .snippets/text/products/native-token-transfers/guides/install-ntt-project.md
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/guides/deploy-to-evm.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#588 Spl token clarification
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/native-token-transfers/overview.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#587 Martinh/update sdk v3.4.0
  .snippets/text/products/reference/chain-ids/chain-ids.md
  .snippets/text/products/reference/consistency-levels/consistency-levels.md
  .snippets/text/products/reference/contract-addresses/core-contracts.md
  .snippets/text/products/reference/contract-addresses/relayer.md
  .snippets/text/products/reference/contract-addresses/token-bridge.md
  .snippets/text/products/reference/supported-networks/connect.md
  .snippets/text/products/reference/supported-networks/multigov.md
  .snippets/text/products/reference/supported-networks/ntt.md
  .snippets/text/products/reference/supported-networks/token-bridge.md
  .snippets/text/products/reference/testnet-faucets/testnet-faucets.md
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-multigov.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-reference.txt
  llms-files/llms-relayers.txt
  llms-files/llms-settlement.txt
  llms-files/llms-token-bridge.txt
  llms-files/llms-transfer.txt
  llms-files/llms-typescript-sdk.txt
  llms-full.txt
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#581 SEO August Report
  .snippets/code/products/connect/configuration/configuration-v0/index.ts
  llms-files/llms-cctp.txt
  llms-files/llms-connect.txt
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-transfer.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/cctp-bridge/get-started.md
  products/connect/configuration/data.md
  products/queries/faqs.md
  products/queries/guides/use-queries.md
  products/token-transfers/native-token-transfers/faqs.md
  products/token-transfers/native-token-transfers/guides/deploy-to-solana.md
  products/token-transfers/native-token-transfers/guides/troubleshoot.md
  products/token-transfers/wrapped-token-transfers/get-started.md
  products/token-transfers/wrapped-token-transfers/guides/attest-tokens.md
  products/token-transfers/wrapped-token-transfers/tutorials/multichain-token.md
  tools/.solidity-sdk/.get-started.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C0 - Low

#584 Martinh/cctp vs wtt
  llms-files/llms-cctp.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/cctp-bridge/overview.md
Labels: A0 - New Content, B1 - Ready to Merge

#590 Martinh/product videos
  llms-files/llms-ntt.txt
  llms-files/llms-queries.txt
  llms-files/llms-settlement.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/queries/faqs.md
  products/settlement/get-started.md
  products/settlement/overview.md
  products/token-transfers/native-token-transfers/concepts/architecture.md
  products/token-transfers/native-token-transfers/faqs.md
  products/token-transfers/native-token-transfers/get-started.md
Labels: A0 - New Content, B1 - Ready to Merge

#600 Fix typo
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-full.txt
  products/token-transfers/native-token-transfers/configuration/access-control.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C0 - Low

#601 Martinh/token transfers update
  llms-files/llms-ntt.txt
  llms-files/llms-transfer.txt
  llms-files/llms-wtt.txt
  llms-full.txt
  products/token-transfers/overview.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#605 Martinh/update multigov link
  llms-files/llms-multigov.txt
  llms-full.txt
  products/multigov/guides/upgrade-evm.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge
